language: r
sudo: required

r:
  - oldrel
  - release
  - devel

cache: packages

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    recipients:
      - jeff.goldsmith@columbia.edu
    on_success: change
    on_failure: always

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'